USE master
GO
DROP DATABASE SQLQLTC
GO
CREATE DATABASE SQLQLTC
GO
USE SQLQLTC
GO

CREATE TABLE KHACHHANG (
  IDKH INT PRIMARY KEY NOT NULL IDENTITY(1,1),
  TENKHACHHANG NVARCHAR(255),
  SOCMND INT,
)
GO

CREATE TABLE TIECCUOI (
  IDTC INT PRIMARY KEY NOT NULL IDENTITY(1,1),
  TENCHURE VARCHAR(255),
  TENCODAU VARCHAR(255),
  NGAY DATE,
  CA BIT,
  IDKHACHHANG INT FOREIGN KEY REFERENCES dbo.KHACHHANG(IDKH),
)
GO

CREATE TABLE THUCDON
(
	IDTD INT PRIMARY KEY NOT NULL IDENTITY(1,1),
	SOLUONGMONAN INT NOT NULL,
	TONGTIEN DECIMAL(19,4),
	GHICHU NVARCHAR(1024),
	IDTIECCUOI INT UNIQUE FOREIGN KEY REFERENCES dbo.TIECCUOI(IDTC),
)
GO

CREATE TABLE LOAIMA
(
	IDLOAI INT PRIMARY KEY NOT NULL IDENTITY(1,1),
	TENLOAI NVARCHAR(255)
)
GO

CREATE TABLE MONAN
(
   IDMA INT PRIMARY KEY NOT NULL IDENTITY(1,1),
   TENMON NVARCHAR(255),
   DONGIA DECIMAL(19,4),
   GHICHU NVARCHAR(1024),
   IDLOAI INT FOREIGN KEY REFERENCES dbo.LOAIMA(IDLOAI)
)
GO

CREATE TABLE THUCDON_MONAN (
	IDTD INT NOT NULL,
	IDMA INT NOT NULL,
	CONSTRAINT PK_TDMA PRIMARY KEY (IDTD,IDMA)
)
GO

CREATE TABLE DICHVU (
  IDDV INT PRIMARY KEY NOT NULL IDENTITY(1,1),
  TENDV NVARCHAR(255),
  DONGIA DECIMAL(19,4),
  MOTA NVARCHAR(1024),
  GHICHU NVARCHAR(1024)
)
GO

CREATE TABLE HOPDONG (
  IDHD INT PRIMARY KEY NOT NULL IDENTITY(1,1),
  SLMANAN INT,
  SLDICHVU INT,
  TONGTIENDV DECIMAL(19,4),
  TONGTIENMA DECIMAL(19,4),
  TTTHANHTOAN DECIMAL(19,4),
  SOTIENDATCOC DECIMAL(19,4),
  QUYDINH NVARCHAR(1024),
  ID_TIECCUOI INT UNIQUE FOREIGN KEY REFERENCES dbo.TIECCUOI(IDTC),
  ID_KHACHHANG INT FOREIGN KEY REFERENCES dbo.KHACHHANG(IDKH)
)
GO

CREATE TABLE SUDUNGDV (
	IDDV INT NOT NULL,
	IDHD INT NOT NULL,
	CONSTRAINT PK_HDDV PRIMARY KEY (IDHD,IDDV)
)
GO

CREATE TABLE HOADON (
	IDHOADON INT NOT NULL PRIMARY KEY,
	TONGTIENTHANHTOAN DECIMAL(19,4),
	PHIPHAT DECIMAL(19,4),
	TONGTIENDV DECIMAL(19,4),
	TONGTIENMA DECIMAL(19,4),
	IDHOPDONG INT UNIQUE FOREIGN KEY REFERENCES dbo.HOPDONG(IDHD),
)
GO

CREATE TABLE BAOCAOTHANG (
	IDBC INT NOT NULL PRIMARY KEY,
	THANGNAM DATE,
	TRUNGBINHDOANHTHU DECIMAL(19,4),
	SOLUONGPHAT INT,
	SOLUONGTIEC INT,
)

CREATE TABLE UserRole (
	IDRole INT IDENTITY (1,1) PRIMARY KEY,
	DisplayName nvarchar(max)
)
GO

CREATE TABLE Users (
	IDUS int identity(1,1) primary key,
	DisplayName nvarchar(max),
	UserName nvarchar(100),
	Password nvarchar(max),
	IdRole int not null
	FOREIGN KEY (IdRole) REFERENCES UserRole(IDRole)
)
GO

CREATE TABLE LOAISANH (
	IDLOAISANH int identity(1,1) primary key not null,
	TENLOAI nvarchar(max),
    DGBANTOITHIEU DECIMAL(19,4)											
)
GO

CREATE TABLE SANH (
	IDSANH int identity(1,1) primary key not null,
	TENSANH nvarchar(255),	
	SLBANTOIDA int,	
	GHICHU nvarchar(max),
	TRANGTHAI bit,
	IDTIECCUOI int FOREIGN KEY (idtieccuoi) REFERENCES dbo.TIECCUOI(IDTC),
	IDLOAI int FOREIGN KEY (idloai) REFERENCES dbo.LOAISANH(IDLOAISANH)
)
GO




