//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeddingApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAOCAOTHANG
    {
        public int IDBC { get; set; }
        public Nullable<System.DateTime> THANGNAM { get; set; }
        public Nullable<decimal> TRUNGBINHDOANHTHU { get; set; }
        public Nullable<int> SOLUONGPHAT { get; set; }
        public Nullable<int> SOLUONGTIEC { get; set; }
    }
}
