//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeddingApp.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SQLQLTCEntities : DbContext
    {
        public SQLQLTCEntities()
            : base("name=SQLQLTCEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DICHVU> DICHVUs { get; set; }
        public virtual DbSet<DICHVU_THUCDON> DICHVU_THUCDON { get; set; }
        public virtual DbSet<HOPDONG> HOPDONGs { get; set; }
        public virtual DbSet<KHACHHANG> KHACHHANGs { get; set; }
        public virtual DbSet<MONAN> MONANs { get; set; }
        public virtual DbSet<THUCDON> THUCDONs { get; set; }
        public virtual DbSet<THUCDON_MONAN> THUCDON_MONAN { get; set; }
        public virtual DbSet<TIECCUOI> TIECCUOIs { get; set; }
    }
}
