//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeddingApp.Model
{
    using System;
    using System.Collections.Generic;
    using WeddingApp.ViewModel;

    public partial class DICHVU : BaseViewModel
    {     

        private int _IDDV;
        public int IDDV { get => _IDDV; set { _IDDV = value; OnPropertyChanged(); } }

        private string _TENDV;
        public string TENDV { get => _TENDV; set { _TENDV = value; OnPropertyChanged(); } }

        private Nullable<decimal> _DONGIA;
        public Nullable<decimal> DONGIA { get => _DONGIA; set { _DONGIA = value; OnPropertyChanged(); } }

        private string _MOTA;
        public string MOTA { get => _MOTA; set { _MOTA = value; OnPropertyChanged(); } }

        private string _GHICHU;
        public string GHICHU { get => _GHICHU; set { _GHICHU = value; OnPropertyChanged(); } }
    }
}
