//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeddingApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOADON
    {
        public int IDHOADON { get; set; }
        public Nullable<decimal> TONGTIENTHANHTOAN { get; set; }
        public Nullable<decimal> PHIPHAT { get; set; }
        public Nullable<decimal> TONGTIENDV { get; set; }
        public Nullable<decimal> TONGTIENMA { get; set; }
        public Nullable<int> IDHOPDONG { get; set; }
    
        public virtual HOPDONG HOPDONG { get; set; }
    }
}
