//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeddingApp.Model
{
    using System;
    using System.Collections.Generic;
    using WeddingApp.ViewModel;

    public partial class SANH : BaseViewModel
    {
        private int _IDSANH { get; set; }
        public int IDSANH { get => _IDSANH; set { _IDSANH = value; OnPropertyChanged(); } }

        private string _TENSANH { get; set; }
        public string TENSANH { get => _TENSANH; set { _TENSANH = value; OnPropertyChanged(); } }

        private Nullable<int> _SLBANTOIDA { get; set; }
        public Nullable<int> SLBANTOIDA { get => _SLBANTOIDA; set { _SLBANTOIDA = value; OnPropertyChanged(); } }

        private Nullable<decimal> _DGBANTOITHIEU { get; set; }
        public Nullable<decimal> DGBANTOITHIEU { get => _DGBANTOITHIEU; set { _DGBANTOITHIEU = value; OnPropertyChanged(); } }

        private string _GHICHU { get; set; }
        public string GHICHU { get => _GHICHU; set { _GHICHU = value; OnPropertyChanged(); } }

        private Nullable<int> _IDTIECCUOI { get; set; }
        public Nullable<int> IDTIECCUOI { get => _IDTIECCUOI; set { _IDTIECCUOI = value; OnPropertyChanged(); } }

        private Nullable<bool> _TRANGTHAI { get; set; }
        public Nullable<bool> TRANGTHAI { get => _TRANGTHAI; set { _TRANGTHAI = value; OnPropertyChanged(); } }

        private TIECCUOI _TIECCUOI { get; set; }
        public virtual TIECCUOI TIECCUOI { get => _TIECCUOI; set { _TIECCUOI = value; OnPropertyChanged(); } }

        private Nullable<int> _IDLOAI { get; set; }
        public Nullable<int> IDLOAI { get => _IDLOAI; set { _IDLOAI = value; OnPropertyChanged(); } }

        private LOAISANH _LOAISANH { get; set; }
        public virtual LOAISANH LOAISANH { get => _LOAISANH; set { _LOAISANH = value; OnPropertyChanged(); } }
    }
}
