//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeddingApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class THUCDON
    {
        public int IDTD { get; set; }
        public int SOLUONGMONAN { get; set; }
        public Nullable<decimal> TONGTIEN { get; set; }
        public string GHICHU { get; set; }
        public Nullable<int> IDTIECCUOI { get; set; }
    
        public virtual TIECCUOI TIECCUOI { get; set; }
    }
}
